name: Test CI
on:
  push:
    branches:
      - ch-coveralls-intergration
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
      - name: Badge Action
        uses: emibcn/badge-action@v2.0.2
      - uses: actions/checkout@v1
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test --if-present
      - name: Test coverage
        run: |
          npm run test:coverage 
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --debug